[build-system]
requires = ["sphinx-theme-builder>=0.2.0"]
build-backend = "sphinx_theme_builder"

[project]
name = "zcnote-sphinx-theme"
dynamic = ["version"]
description = "A lightweight wrapper theme based on the pydata-sphinx-theme."
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-3-Clause"
authors = [
    {name = "zclab", email = "yshi009@foxmail.com"},
]
dependencies = [
    "sphinx>=8.0, <10",
    "pydata-sphinx-theme>=0.16.0, <0.19.0"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Framework :: Sphinx",
  "Framework :: Sphinx :: Theme",
  "Operating System :: OS Independent",
]

[project.urls]
"Source" = "https://github.com/zclab/zcnote-sphinx-theme"
"Bug Tracker" = "https://github.com/zclab/zcnote-sphinx-theme/issues"

[project.optional-dependencies]
doc = [
    "sphinx_design",
    "myst-parser",
    "sphinx_copybutton",
    "sphinx-togglebutton",
    "sphinxcontrib-mermaid",
    "ablog>=0.11.13"
]
dev = [
    "sphinx-autobuild",
    "build",
    "twine",
]

[project.entry-points."sphinx.html_themes"]
zcnote_sphinx_theme = "zcnote_sphinx_theme"

[tool.sphinx-theme-builder]
theme-name = "zcnote_sphinx_theme"
node-project-dir = "."
build-command = ["npm", "run", "build"]
node-version = "20.11.1"
ignore-files = [
    ".github",
    ".idea",
    ".vscode",
    "docs",
    "scripts",
    "tests"
]
