[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zcnote-sphinx-theme"
dynamic = ["version"]
description = "A customized Sphinx theme based on pydata-sphinx-theme."
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-3-Clause"
authors = [
    {name = "zclab", email = "yshi009@foxmail.com"},
]
dependencies = [
    "sphinx>=8.0, <10",
    "pydata-sphinx-theme>=0.16.0, <0.18.0"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Framework :: Sphinx",
  "Framework :: Sphinx :: Theme",
  "Operating System :: OS Independent",
]

[project.urls]
"Source" = "https://github.com/zclab/zcnote-sphinx-theme"

[project.optional-dependencies]
doc = [
    "sphinx_design",
    "myst-parser",
    "sphinx_copybutton",
    "sphinx-togglebutton",
]

[project.entry-points."sphinx.html_themes"]
zcnote_sphinx_theme = "zcnote_sphinx_theme"


[tool.hatch.version]
path = "src/zcnote_sphinx_theme/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/zcnote_sphinx_theme"]

[tool.hatch.build.targets.wheel.force-include]
"src/zcnote_sphinx_theme/theme" = "zcnote_sphinx_theme/theme"
