[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zcnote-sphinx-theme"
version = "0.1.0"
description = "A customized Sphinx theme based on pydata-sphinx-theme."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "sphinx>=8.0",
    "pydata-sphinx-theme>=0.16.0"
]

[project.entry-points."sphinx.html_themes"]
# 这是让 Sphinx 能通过 html_theme = 'zcnote_sphinx_theme' 自动找到该包的关键
zcnote_sphinx_theme = "zcnote_sphinx_theme"

[tool.setuptools.packages.find]
where = ["src"]
