[theme]
inherit = pydata_sphinx_theme
stylesheet = styles/zcnote-sphinx-theme.css
sidebars = sidebar-nav-bs

[options]
primary_sidebar_end = sidebar-collapse
footer_start = copyright, sphinx-version
footer_center =
footer_end = zcnote-theme-version

# The default is "header", but it can also be "sidebar"
nav_style = header
home_page_in_toc = false
hide_header = false
relocate_header =
