[theme]
inherit = pydata_sphinx_theme
# 覆盖或追加默认样式
stylesheet = styles/zcnote-sphinx-theme.css

[options]
footer_start = copyright, sphinx-version
footer_center =
footer_end = zcnote-theme-version

enable_collapse_sidebar = true

# 导航模式控制：
# 'header' -> 默认 pydata 风格（顶部展示顶级目录，左侧展示子目录）
# 'sidebar' -> sphinx-book-theme 风格（左侧展示全量目录树，顶部不展示）
nav_style = header
home_page_in_toc = false
